### ISSUE TITLE
Custom CSS: add flexbox support

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1534]
Try entering the following the custom CSS editor:

```css
.container {
  justify-content: space-around;
}
```

`justify-content: space-around;` will be stripped on save.

Reported here:
https://wordpress.org/support/topic/css-editor-issue?replies=1
