### ISSUE TITLE
Image Compare Block: themes can break the image layout

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16036]
Some themes can break the image layout, with CSS like this:

```css
.hentry.post img {
    max-width: 100% !important;
    height: auto;
}
```

Maybe we should try to work around that by being more specific on our end?

cc @mkaz
