### ISSUE TITLE
Search: Scrolling minimal results view eventually triggers mobile view

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#16693]
Happens on greyhoundresearch.com in a number of browsers. Unsure if it is specific to this theme or not.

![gif](https://user-images.githubusercontent.com/820871/89219361-dbeb7380-d58c-11ea-9f2e-10c7f2a93012.gif)

**Comment by JoshuaGoode** [comment]
Related to internal discussion on p9F6qB-5FA-p2

Please update there once resolved so we can close out the request.

**Comment by jsnmoon** [comment]
This is being caused by a styling issue. As a temporary fix, one can apply the following styling:

```css
.jetpack-instant-search__result-expanded__copy-container >.jetpack-instant-search__result-expanded__path {
    max-width: 40em;
}
```

I will follow-up with a PR to permanently fix this issue shortly.
