### ISSUE TITLE
Repo Gardening: extra label detection to a config file

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19897]
The Repo Gardening action's `addLabels` task currently relies on detecting paths that are hardcoded in the action:
https://github.com/Automattic/jetpack/blob/a5f167cbc51792848f4fa53e57801bd709527bfa/projects/github-actions/repo-gardening/src/tasks/add-labels/index.js#L81-L91

While this works, it also means that the task cannot be used by third-parties unless their file structure matches ours. That is not ideal. 

Let's aim to have those paths defined in a config file, maybe a `.json` file that would live in the `.github` directory of any repo using the action and that task, and where we would define a list of label names and matching patterns that could be used by the action.

Noting that this config file would have to support more complex patterns, such as the ones we use here:
https://github.com/Automattic/jetpack/blob/a5f167cbc51792848f4fa53e57801bd709527bfa/projects/github-actions/repo-gardening/src/tasks/add-labels/index.js#L104-L123

************

Related PR: #19891

**Comment by anomiex** [comment]
For the Required Review action I went with yaml data, which can be passed directly from the workflow or stored as a file in the repo. See https://github.com/Automattic/action-required-review/blob/8c79b3706c8e0022be1dbb106c0f8475d07d9c9c/src/main.js#L14-L37. The nice thing about yaml is that it can easily include comments, and the quoting is easier for humans to deal with.

> Noting that this config file would have to support more complex patterns, such as the ones we use here:

Off the top of my head, maybe something like this?
```yaml
# Mappings apply to any capturing group with the corresponding name, and map matched values to label values.
# The "*unmatched*" key is special, indicating how to handle entries not in the map.
#  - literal: Use the matched value unchanged. This should probably be the default.
#  - transform: Capitalize dash-separated words then join with spaces.
#  - error: Report an error.
# If no mapping is specified for a group name, it winds up defaulting to "literal".
mappings:
  ptype:
    editor-extensions: Block
    github-actions: Action
    packages: Package
    plugins: Plugin
    js-packages: JS Package
    '*unmatched*': error
  name:
    sharedaddy: Sharing
    shortcodes: Shortcodes / Embeds
    # ...
    '*unmatched*': transform

# Patterns map JavaScript-style regular expressions to labels.
# Named capturing groups in the regex are passed through corresponding mappings (above) before being substituted into labels.
# Note slashes don't need to be escaped in the regexes, and regexes are implicitly anchored at the start.
patterns:
  # Projects
  - file: 'projects/(?<ptype>[^/]*)/(?<name>[^/]*)/'
    labels: [ '[${ ptype }] ${ name }' ]

  # Additional label for actions
  - file: 'projects/github-actions/'
    labels: [ 'Actions' ]

  # Modules
  - file: 'projects/plugins/jetpack/modules/(?<name>[^/]*)/'
    labels: [ '${ name }' ]
  - file: 'projects/plugins/jetpack/tests/php/modules/(?<name>[^/]*)/'
    labels: [ '${ name }', 'Unit Tests' ]

  # ...
```
