### ISSUE TITLE
Boost: Critical CSS includes admin bar on Atomic sites

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20549]
Generating Critical CSS on Atomic sites includes admin bar styles.

Sample CSS:
```css
@media all{
    #wpadminbar #wp-admin-bar-debug-bar{
        float:right
    }
    #wpadminbar #wp-admin-bar-debug-bar ul{
        right:0
    }
    #querylist,#querylist pre{
        text-align:left;
        font-size:12px
    }
```

#### Steps to reproduce the issue
1. Run Jetpack Boost on a site hosted on the Atomic infrastructure.
2. Generate Critical CSS.
3. Look at the Generated Critical CSS; confirm selectors like `#wpadminbar #wp-admin-bar-debug-bar`

#### What I expected
Critical CSS should never include styles which only apply to logged in users.
