### ISSUE TITLE
Boost: Investigate the possibility to trigger Boost E2E tests Github workflow from changes on dependent Jetpack packages and have it as required in this context

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#21707]
Boost is [dependent](https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/composer.json) on the following packages from the Monorepo:

- projects/packages/admin-ui
- projects/packages/autoloader
- projects/packages/config
- projects/packages/connection
- projects/packages/device-detection
- projects/packages/lazy-images
- projects/packages/terms-of-service
- projects/packages/tracking

@thingalon suggested that it would be a good idea to have the Boost E2E tests Github workflow triggered when changes are happening in these packages.

Right now the workflow is [triggered only when they are changes in the Boost plugins](https://github.com/Automattic/jetpack/blob/master/.github/workflows/e2e-tests-boost.yml) but I guess we can just add an additional path to trigger the workflow which should be straightforward enough by editing the [Github e2e-tests-boost.yml workflow file](https://github.com/Automattic/jetpack/blob/master/.github/workflows/e2e-tests-boost.yml).

The question is: Is it possible to have the Boost E2E tests Github workflow triggered AND marked as 'Required' only in the context that Boost files changes or on any of the related dependent packages file changes too? I guess it might need to be done via [branch protection rules](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)?

**Comment by davidlonjon** [comment]
@adimoldovan, @anomiex  @jeherve would you have any pointer or advice on this question?

**Comment by anomiex** [comment]
Being marked as "required" is an all-or-nothing thing. But while a skipped _workflow_ doesn't satisfy the requirement, a skipped _job_ does. The requirement logic seems to be "workflow ran at least once, and no instance of the job failed".

You'll probably want to move the skipping to the job level anyway. Your best course of action is probably to make use of `.github/files/list-changed-projects.php` which already takes into account dependencies. Maybe something like this (off the top of my head):
```yaml
name: Jetpack Boost E2E Tests

on:
  pull_request:
  push:
    branches: [master]
concurrency:
  group: e2e-tests-boost-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "Check if Boost E2E tests should run"
    runs-on: ubuntu-latest
    timeout-minutes: 1  # 2021-11-12: Should only take a second.
    outputs:
      boost: ${{ steps.check.outputs.boost }}
    steps:
      - uses: actions/checkout@v2
      # For pull requests, list-changed-projects.php needs the merge base.
      - name: Deepen to merge base
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/deepen-to-merge-base
      - id: check
        run: |
          CHANGED="$(.github/files/list-changed-projects.php --debug)"
          BOOST="$(jq '.["plugins/boost"] // false' <<<"$CHANGED")"
          echo "::set-output name=boost::${BOOST}"

  e2e-tests:
    name: "Boost E2E tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: check
    if: needs.check.outputs.boost == 'true'

    steps:
      ...
```
