### ISSUE TITLE
Required Review Github Action should ignore overridden "Approved" reviews

### ISSUE THREAD

**Issue by fallard84** [Automattic/jetpack#23083]
### Impacted plugin

None / Other

### Steps to Reproduce

1. Configure the Require Review Github Action
2. Create a PR that meets the requirements
3. Approve the PR with a user that meets the requirements
4. Dismiss the approval

### A clear and concise description of what you expected to happen.

When the review has been dismissed, the requirement should become unmet, and change the PR check to waiting for review.

### What actually happened

The PR check still indicates that the required reviews have been provided, and the GH action logs shows the requirement is satisfied.

### Other information

Looking at the [code](https://github.com/Automattic/jetpack/blob/master/projects/github-actions/required-review/src/reviewers.js#L17-L29), we are using the list reviews API, which list the historical information of reviews, and not necessarily the latest state. We should only consider the latest review state for each user.

### Operating System

Other

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
> When the review has been dismissed, the requirement should become unmet, and change the PR check to waiting for review.

That's what I'm seeing in my test (in #23018).

- When I first approved the PR, the required review check started passing:
<img width="1095" alt="Screenshot 2022-02-24 at 16 00 38" src="https://user-images.githubusercontent.com/426388/155549800-2645f8a2-de8a-454f-b827-d90419e8b2ba.png">

- When I then dismissed it, the workflow ran again and the test went back to pending:

<img width="1022" alt="Screenshot 2022-02-24 at 16 01 55" src="https://user-images.githubusercontent.com/426388/155550289-c9d089e8-0f61-464c-a1b5-6f64586af7ca.png">

Do you experience something different on your end? Is your workflow configured the same way as ours here?
https://github.com/Automattic/jetpack/blob/4615a9477e799d1bd447f573edd34cf4e7c3e1d4/.github/workflows/required-review.yml#L1-L5

**Comment by fallard84** [comment]
Yes, I have this similar configuration on my end:
``` yaml
name: Required review check
on:
  pull_request_review:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest

    # GitHub should provide a "pull_request_review_target", but they don't and
    # the action will fail if run on a forked PR.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.pull_request.base.ref == 'main'

    steps:
      - uses: Automattic/action-required-review@v2.2.2
        with:
          requirements: |
            - paths: unmatched
              teams:
                - maintenance
          status: Required review
          token: ${{ secrets.GH_TOKEN }}
```

But my description was misleading, I said dismiss, but what I meant was that the reviewer changed his "Approved" review to something else (e.g. "Request for change" or "Request a new review").

The "requested changes" did not cause the action to put back the state to pending.
![image](https://user-images.githubusercontent.com/10320763/155553172-3f672483-cb78-4dd8-99bf-6c751941ea28.png)
