### ISSUE TITLE
Boost: Critical CSS doesn't rewrite relative URLs unless they are in quotes

### ISSUE THREAD

**Issue by AndisGrossteins** [Automattic/jetpack#26306]
### Impacted plugin

Boost

### Steps to Reproduce

1. Have a theme (/wp-content/themes/[custom]/style.css) with following CSS snippet and others with similar relative URLs:
````css
.site-main {
    background: #f9fff2 url(images/site-background.png) repeat center
}
````
2. And corresponding image files in  `/wp-content/themes/[custom]/images/`
3. Enable critical CSS feature in Jetpack Boost
4. Boost generates and inserts an inline stylesheet containing same URLs unmodified resulting in requests for non-existent`https://example.com/some-page/images/site-background.png` on every page

### A clear and concise description of what you expected to happen.

I expected Jetpack Boost to rewrite the relative URLs to absolute URLs in the critical CSS snippet.

### What actually happened

The resource URLs are not rewritten resulting in multiple 404s.

### Other information

While not using quotation marks might be uncommon, it's still valid CSS.
According to [latest CSS spec](https://www.w3.org/TR/css-values-4/#funcdef-url):
> For legacy reasons, a [url()](https://www.w3.org/TR/css-values-4/#funcdef-url) can be written without quotation marks around the URL itself, in which case it is [specially-parsed](https://www.w3.org/TR/css-syntax-3/#consume-a-url-token) as a [<url-token>](https://www.w3.org/TR/css-syntax-3/#typedef-url-token) [[CSS-SYNTAX-3]](https://www.w3.org/TR/css-values-4/#biblio-css-syntax-3).

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Workaround details

The issue can be avoided by quoting all resource URLs in CSS files, which might not be a viable solution for most Jetpack users.

**Comment by dilirity** [comment]
@thingalon do you happen to know if anyone has worked on this and probably resolved it? I'm unable to reproduce it.

My test setup is using the `twentytwentyfour` theme with these styles in `style.css` (enqueued via PHP):

```css
.page-id-7006 .site-background {
    background: #f9fff2 url(images/site-background.png) repeat center
}
```

The screenshot is from a page `/test-page-3/` (so it's not the root of the site).
![CleanShot 2024-03-19 at 17 00 22](https://github.com/Automattic/jetpack/assets/11799079/d46caaef-76d4-439a-ab9e-8a05d14ecef0)

So the CSS is valid and working.

After generating critical CSS, the URL is correct (snippet truncated):

```css
@media all{.page-id-7006 .site-background{background:#f9fff2 url(http://jetpack-boost.test/wp-content/themes/twentytwentyfour/images/site-background.png) repeat center}}
```

I can't seem to find a way to break it.
