### ISSUE TITLE
Carousel enhancement: Add setting to hide image title & caption

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#26821]
### Impacted plugin

Jetpack

### What

Add a user-facing setting to hide the image title and caption, similar to the existing settings for hiding comments and EXIF metadata.

### How

Sometimes users to want the carousel to simply display their images and nothing else.

Currently, there is no easy way to achieve that without a bit of manual work (CSS customization or manually removing all image titles/captions from the media gallery).

This experience could be improved by introducing a setting to hide image titles/captions. We could also lump this in with a setting to hide the "i" button and information panel altogether.

![Markup on 2022-10-13 at 10:33:18](https://user-images.githubusercontent.com/17372274/195626395-441d81f8-d50d-4b7c-bdbd-d5f8a94f4e4c.png)

This was previously brought up here:

https://github.com/Automattic/jetpack/issues/15224

But that issue was closed after we added the setting to hide only comments.

**Comment by cliffordp** [comment]
CSS to hide Title and "i" button until such an option is available:
```css
.jp-carousel-overlay .jp-carousel-photo-title-container,
.jp-carousel-overlay .jp-carousel-photo-icons-container
{
	display: none;
}
```
