### ISSUE TITLE
Custom CSS: multiple display for flexbox layout

### ISSUE THREAD

**Issue by creativejuiz** [Automattic/jetpack#2742]
Hi there,

I'm working on a custom CSS for a WordCamp website, and I was trying to use the flexbox property with no success. I was using a code like that:
```css
.site-main {
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-flex-direction: column;
	-ms-flex-direction: column;
	flex-direction: column;
}
```
My console in Firefox shown me the flex-direction property, but the display: flex; was absent. Finally, I think CSSTidy is removing duplicate properties keeping the first declared.

To keep cross-browser compatibility, I used hacks and wrote:
```css
/* Internet Explorer Hack */
_:-ms-input-placeholder, :root .site-main {
	display: -ms-flexbox;
}
/* Safari, Chrome & Opera hack */
.site-main:not(*:root) {
	display: -webkit-flex;
}
.site-main {
	display: flex;
	-webkit-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-flex-direction: column;
	-ms-flex-direction: column;
	flex-direction: column;
}
```
And it works.
I don't know if it's a bug, CSSTidy do its work, but why is it removing duplicate properties? The browser knows what it have to do with duplicate properties, CSSTidy don't.

Thank you.
