### ISSUE TITLE
Share Buttons: Icon version display issues in Jetpack 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#29083]
### Impacted plugin

Jetpack

### Quick summary

The icon-only view of the Jetpack Share buttons has a little extra padding in the 11.9-a.5-4226835663-g12a91bfc RC.

### Steps to reproduce

1. Start with a test site running the 11.9-a.5-4226835663-g12a91bfc RC.
2. Enable share buttons.
3. Set the share buttons to show Icon Only.

### A clear and concise description of what you expected to happen.

That the icons would display in a round circle.

### What actually happened

The icons display in a slightly "off" circle.

![image](https://user-images.githubusercontent.com/177561/220478822-4069c287-832f-4e9f-97dc-01a2abb5559c.png)

It looks like it's related to [this change](https://github.com/Automattic/jetpack/pull/28961/files#diff-ef13fe1c8b6bcb23f869c29275061061e587ac353ac9c1a57469c8018fb708d1R128) for the official button styles.

### Impact

Some (< 50%)

### Available workarounds?

Yes. Add the following CSS to the site:
```css
.sd-social-icon .sd-content ul li a.sd-button>span {
	margin-left: 0;
}
```

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
Pending a new release that will include a fix, this bit of CSS should help:

```css
.sd-social-icon .sd-content ul li a.sd-button>span {
	margin-left: 0;
}
```
