### ISSUE TITLE
jetpack 3.9.1: Gray line in genericons linkedin icon (social media icons widget)

### ISSUE THREAD

**Issue by jkossen** [Automattic/jetpack#3352]
Just check the attached screenshot; there's a horizontal gray line in the linkedin genericons icon which is used by the social media icons widget.

<img width="464" alt="schermafbeelding 2016-01-27 om 21 13 01" src="https://cloud.githubusercontent.com/assets/365837/12626828/e8438382-c53a-11e5-9251-4d22b33d935c.png">

**Comment by jeherve** [comment]
That line might be added by your theme. Could you post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.me/contact-support/

**Comment by jkossen** [comment]
Sure, it's at https://creativette.nl/ (the icons are shown at the bottom / footer)

**Comment by jeherve** [comment]
Thanks! That line is added by your theme, on line 1176 of your theme's stylesheet (`style.css`):

```css
.widget li:last-child {
	padding-bottom: 6px;
	border-bottom: 1px solid rgba(0,0,0, 0.08);
	}
```

You can remove it for that specific widget by adding the following to your theme stylesheet, or to your custom CSS editor under Appearance > Edit CSS in your dashboard:

```css
.widget_wpcom_social_media_icons_widget  li:last-child {
		border-bottom: 0 none;
	}
```
