### ISSUE TITLE
Widget Visibility: option gets deleted by mistake on i18n interfaces

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3382]
See this video of Appearance > Widgets on a French website:
http://i.wpne.ws/f5QG

Since we can't use short labels in each and every language, we'd need to make sure the interface still works, even with long labels.

**Comment by eliorivero** [comment]
The click issue can be solved inserting this in their corresponding rules:
```css
.widget-conditional .condition select {
    position: relative;
    z-index: 2;
}
.widget-conditional .condition-control a {
    position: relative;
    z-index: 1;
}
```
However, we still have the issue of truncated labels, I have it in spanish too.

So how about converting these text links to icons?

In Widgets screen
<img width="412" alt="widget-visibility0" src="https://cloud.githubusercontent.com/assets/1041600/12920486/9827f742-cf27-11e5-8f97-1aa8c547a9a0.png">
<img width="418" alt="widget-visibility1" src="https://cloud.githubusercontent.com/assets/1041600/12920488/98d878c4-cf27-11e5-824a-1f05c8b460e5.png">

In Customizer
<img width="284" alt="widget-visibility2" src="https://cloud.githubusercontent.com/assets/1041600/12920581/f2b6dcb4-cf27-11e5-9707-80a56b604534.png">

Pinging @jeffgolenski for design feedback.
