### ISSUE TITLE
Related Posts: display issue in Twenty Sixteen / Firefox

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3434]
This can be reproduced on desktop as well as in the Firefox for mobile app on Android, on a site using the Twenty Sixteen theme.

The line appearing above the Related Posts headline isn't sticked to the left of the page:

![fdgicuj](https://cloud.githubusercontent.com/assets/426388/13222598/ee581508-d980-11e5-860b-d783641e7bbd.png)

This can be fixed with the following:

```css
.jp-relatedposts::before, .jp-relatedposts:last-child::after {
	left: 0;
}
```

Reported here:
https://wordpress.org/support/topic/responsiveness-issue-with-jetpack-related-posts-in-firefox
