### ISSUE TITLE
Custom CSS: break-inside stripped on save

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3671]
### Steps to reproduce:

1. Add the following code to Appearance > Edit CSS:

```css
li {
-webkit-column-break-inside: avoid;
          page-break-inside: avoid;
               break-inside: avoid;
}
````

2. Save your changes.
3. `-webkit-column-break-inside: avoid;` is removed.

Reported here:
https://wordpress.org/support/topic/css-property-rejected-by-jetpacks-custom-css-module?replies=1&view=all

**Comment by RCowles** [comment]
Noting that this also applies to [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select). So, the following example will be stripped as well:
```
.post {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

**Comment by jeherve** [comment]
Same problem with `text-fill-color`:

```css
.post {
    -webkit-text-fill-color: #000000;
}
```

We'll need to add support for all those as well:
https://webkit.org/blog/85/introducing-text-stroke/

Reported here:
https://wordpress.org/support/topic/css-editor-dumping-invalid-css/
