### ISSUE TITLE
Custom CSS: Vendor prefix being stripped

### ISSUE THREAD

**Issue by mauryaratan** [Automattic/jetpack#402]
There is something wrong with Custom CSS module. When I try to enter the following code:

``` css
html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

The second line with `-moz-osx-font-smoothing: grayscale;` is stripped.

Here is a gif to make it more clear:

![jetpack-css](https://cloud.githubusercontent.com/assets/1505631/2553197/820da230-b6a2-11e3-88ef-7426755b847d.gif)

Checked both under current stable release and Github branch.
