### ISSUE TITLE
Necessary Permissions for Required Review action are unclear or incomplete

### ISSUE THREAD

**Issue by wAuner** [Automattic/jetpack#40626]
### Impacted plugin

None / Other

### Quick summary

I'm failing to set up the [Required Review](https://github.com/marketplace/actions/required-review) GitHub action.
I did create a GitHub app with these permissions:
* Repository permissions:
  * Checks: read and write
  * Metadata: read
  * Pull requests: read
* Organization permissions:
  * Members: read 
But the action still fails with this trace:
```
Error: Resource not accessible by integration
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/Automattic/action-required-review/node_modules/.pnpm/@octokit+request@5.6.3/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.status (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/reporter.js:31:1)
    at main (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/main.js:94:1)
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/Automattic/action-required-review/node_modules/.pnpm/@octokit+request@5.6.3/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.status (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/reporter.js:[31](https://github.com/eng-citrix/uberAgent/actions/runs/12349225036/job/34459615984#step:4:39):1)
    at main (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/main.js:118:1)
```

The description of the required permissions in the comment is this:
```
# GitHub Access Token. The user associated with this token will show up
    # as the "creator" of the status check, and must have access to read
    # pull request data, create status checks (`repo:status`), and to read
    # your organization's teams (`read:org`).
```

Am I missing a permission or is this something else?

The problematic line seems to be this one: 
https://github.com/Automattic/jetpack/blob/9f6b92002afa3d3812b0018923adb2d3f0a494a6/projects/github-actions/required-review/src/reporter.js#L31

The name suggests that it might be missing the `Commit statuses` permission, but I don't see that mentioned anywhere.

### Steps to reproduce

1. install a GitHub app with the above mentioned permissions
2. Use this pipeline definition:
```
  reviewcheck:
    name: Checking required reviews
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@v1
      id: generate_token
      with: 
        app-id: ${{ vars.REQUIRED_REVIEWS_APP_ID }}
        private-key: ${{ secrets.REQUIRED_REVIEWS_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - uses: Automattic/action-required-review@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        requirements-file: .github/required-review-config.yml
        request-reviews: true
```
