### ISSUE TITLE
Required Review Action reports an empty set for team members

### ISSUE THREAD

**Issue by wAuner** [Automattic/jetpack#41001]
### Impacted plugin

None / Other

### Quick summary

When checking reviewers, the Required Review Action always reports `<empty-set>` for our teams, instead of the actual team members. As a consequence, the checks do never succeed. However, I am able to list the team members from the command line with curl when I use an installation token of the same Github app. We use GitHub Enterprise and the app is installed under the organization. We use `actions/create-github-app-token@v1` with the app id and the private key to create the token within the action that runs the required review job.
In my tests I use the same team slug that's defined in the requirements file.

Any idea what the problem might be? I don't see any useful error message. Is it possible that the output of the team member listing api request is not handled correctly? I used the `orgs/ORG/teams/team-slug/members` endpoint in my command line tests.

### Steps to reproduce

Use the required reviews action with a GitHub App that's installed on an organization.
Check if the team members, listed as required reviewers, can successfully be listed.

### A clear and concise description of what you expected to happen.

The team members should be listed.

**Comment by jeherve** [comment]
> I used the orgs/ORG/teams/team-slug/members endpoint in my command line tests.

That is the endpoint the Required Review action uses too:

- https://github.com/Automattic/jetpack/blob/af9a01ea8d11d4fc73492eb509f17f06712ca30b/projects/github-actions/required-review/src/team-members.js#L39
- https://octokit.github.io/rest.js/v21/#teams-list-members-in-org
- https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members

That said, we haven't tested the action with GitHub entreprise yet. I wonder if that's what's causing the issue here, since by default the API calls are made to `api.github.com`. For entreprise, I think the calls should be made to `github.<yourcompany>.com` instead. I think the `@actions/github` package we use to make the API requests should get that updated base URL automatically:
https://github.com/actions/toolkit/blob/5e8c25d1f5d92a53f2438de763f92d4809dd666f/packages/github/src/internal/utils.ts#L42-L44

However, maybe that's not happening here. 

> We use actions/create-github-app-token@v1 with the app id and the private key to create the token within the action that runs the required review job.

What happens when you use a token created manually instead, with the permissions defined here:
https://github.com/Automattic/jetpack/blob/af9a01ea8d11d4fc73492eb509f17f06712ca30b/projects/github-actions/required-review/README.md#permissions-required

> I don't see any useful error message

What are the different messages logged in the workflow logs? Do you see any success or error messages there?

**Comment by wAuner** [comment]
> I wonder if that's what's causing the issue here, since by default the API calls are made to `api.github.com`. For entreprise, I think the calls should be made to `github.`

I made the calls via curl to `api.github.com` which worked just fine on the command line. 

The only related log message I see is
```
  Checking reviewers...
    Union of these:
      Members of some-team: <empty set>
    => <empty set>
Error: Requirement "Blub" is not satisfied by the existing reviews.
```
no other errors.

The action looks like this:
```
jobs:
  # https://github.com/marketplace/actions/required-review
  reviewcheck:
    name: Checking required reviews
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@v1
      id: generate_token
      with: 
        app-id: ${{ vars.REQUIRED_REVIEWS_APP_ID }}
        private-key: ${{ secrets.REQUIRED_REVIEWS_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - uses: Automattic/action-required-review@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        requirements-file: .github/required-review-config.yml
        request-reviews: true
```

On the command line, I created an installation token based on the installation id and not the app id. Maybe I should try to replace the `app-id: ${{ vars.REQUIRED_REVIEWS_APP_ID }}` with the installation id? That would definitively be a bit inconvenient, since the only way to find out the installation id (that I know of) was to make an API request with JWT. But I'll try that. I encountered the same problem on the command line during my experiments. When I used the app id, instead of installation id, I did get an error. I'll try that and report back.

**Comment by wAuner** [comment]
I just generated an installation token manually which I successfully tested on the command line.
I hard-coded the token for a test run:
```
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - uses: Automattic/action-required-review@v3
      with:
        token: my manually created installation token
        requirements-file: .github/required-review-config.yml
        request-reviews: true
```
I did get the same error with empty set in the pipeline.
