### ISSUE TITLE
Something wrong with latest updade (4.0.4) - font-face in custom CSS not working anymore

### ISSUE THREAD

**Issue by jjgh** [Automattic/jetpack#4173]
I have a custom font-face in the Jetpack custom CSS defined like so:

```css
@font-face {
	font-family: 'Magneto-Bold';
	src: url('http://website.com/wp-content/themes/catch-base-child/fonts/Magneto-Bold.eot?#iefix') format('embedded-opentype'), url('http://website.com/wp-content/themes/catch-base-child/fonts/Magneto-Bold.woff') format('woff'), url('http://website.com/wp-content/themes/catch-base-child/fonts/Magneto-Bold.ttf') format('truetype'), url('http://website.com/wp-content/themes/catch-base-child/fonts/Magneto-Bold.svg#Magneto-Bold') format("svg");
	font-weight: normal;
	font-style: normal;
}
```

This has always been working but after updating from 4.0.3 to 4.0.4 it doesn't work anymore.
