### ISSUE TITLE
Bug in action-required-review

### ISSUE THREAD

**Issue by tureck1y** [Automattic/jetpack#41933]
### Impacted plugin

Jetpack

### Quick summary

**action-required-review** will never satisfy requirements if @someUser is an author of a PR and requirements are configured like this:

```
  teams:
    - all-of:
      - some-team
      - '@someUser'
```

It's impossible to make a self-review and impossible to merge the PR. An empty team should be excluded from the requirements check. An empty virtual team for @someUser in this case/

### Steps to reproduce

1. Configure requirements 

```
- name: Misc
  paths: unmatched
  teams:
    - all-of:
      - some-team
      - '@someUser'
```

2. Open a PR by @someUser as an author
3. Get approval from any user of "some-team"

Result: Requirement "Misc" is not satisfied by the existing reviews.

Expected result: Requirement "Misc" is satisfied by the existing reviews.
 

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Major

**Comment by anomiex** [comment]
I'm hesitant to consider this a bug. Ideally your organization shouldn't have a single point of failure in `@someuser` being personally required to approve everything.

If we do decide to do something about this, I'd prefer adding a condition (name TBD), which for everything under it effectively considers the author as having self-reviewed. That way you would do like
```
    - all-of:
      - some-team
      - new-condition-name-TBD:
        - '@someUser'
```
to allow `@someUser` to auto-"self-review".

Or possibly we could do `is-author` to more specifically check, like
```
    - all-of:
      - some-team
      - any-of:
        - '@someUser'
        - is-author:
          - '@someUser'
```
