### ISSUE TITLE
Sharing: Custom sharing buttons are not displayed properly in IE 11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#816]
Steps to reproduce:
1. Activate Jetpack and the Sharing module
2. In Settings > Sharing, enable a few sharing services 
3. Create a new custom sharing service, and enable it
4. Save your changes
5. Visit your site in IE11

![untitled-2](https://cloud.githubusercontent.com/assets/426388/3537066/3b6a7d0c-081a-11e4-88b1-ee370fb61104.png)

The problem can be solved by adding the following CSS:

``` css
.sd-social-icon .sd-content ul li[class*='share-'] a.share-custom.sd-button {
    top: 0;
}
```

Unfortunately, that change breaks the layout in all other browsers.
